definitions:
  auth.registerRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new account with email and password
      parameters:
      - description: User Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
